package com.escli4j;

public enum Datatype {

    NONE, TEXT, KEYWORD, LONG, INTEGER, SHORT, BYTE, DOUBLE, FLOAT, DATE, BOOLEAN, BINARY, OBJECT, NESTED, GEO_POINT,
    GEO_SHAPE, IP, COMPLETION, TOKEN_COUNT, MURMUR3, ATTACHMENT;
}
