package com.escli4j.mapping;

public enum DataType {

    NONE, STRING, LONG, INTEGER, SHORT, BYTE, DOUBLE, FLOAT, DATE, BOOLEAN, BINARY, OBJECT, NESTED, GEO_POINT,
    GEO_SHAPE, IP, COMPLETION, TOKEN_COUNT, MURMUR3;
}
